### PR TITLE
Django 3 support via compat modules (based on #50)

### PR DESCRIPTION
**Pull request by tony**
Same effect as #50 without `six` dependency (hopefully!)

### CODE REVIEW

**Comment by yakky** [comment]
What's the problem of depending on it explicitly?
I am not sure removing the six dependency is really worth the extra code. Six is going to be always available starting Django 3 as Django itself now depends on it.

**Comment by tony** [comment]
Hm, I'm the only person who brought it up so far, so maybe it's just me. My rationale:

I adopted the packaging aesthetic years ago from here: https://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/ (regarding compat modules)

> What's the problem of depending on it explicitly?

I don't think it's worth pulling in a package over if the only 2.7-compatibility we use is a string type.

> Six is going to be always available starting Django 3 as Django itself now depends on it.

I don't believe core will include it. I could be wrong, but 3.0 removes the vendorization (direct inclusion of it). It sorta looks like it says it, but when I reread it a second time, they say "or switch to six".

> `django.utils.six` - Remove usage of this vendored library or switch to six.

https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

For 3.0.1:

```
.venv ❯ pip show django
Name: Django
Version: 3.0.1
Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Home-page: https://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD
Location: /home/t/work/hsk-django/.venv/lib/python3.8/site-packages
Requires: asgiref, sqlparse, pytz
```

For python 2.2.9:

```
.venv ❯ pip show django
/anName: Django
Version: 2.2.9
Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Home-page: https://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD
Location: /home/t/work/hsk-django/.venv/lib/python3.8/site-packages
Requires: sqlparse, pytz
```

What do you think?

**Comment by yakky** [comment]
@tony WRT six django dependency, I messed it up (on my defense, I was in the middle of the NYE dinner :joy: )
As far as whether depends on six (#50) or just vendor the compatibility code, I will let @FinalAngel make the final call.
We'd better be consistent across all the django CMS related applications

**Comment by tony** [comment]
@FinalAngel in django cms, it went from compat modules in 2014 -> `django.utils.six`  [here](https://github.com/divio/django-cms/blob/4efe4f1eb5620524a836ad926efa9141896e781e/CHANGELOG.rst#304-2014-08-16).

In the here and now, with 2.7 set to sunset and 2.5/2.6 compats no longer needed, I think the use of six is lite enough where a single file compat module may fit the situation. What do you think?

In either event, if you don't end up going with this approach, it's okay to close this :)

**Comment by yakky** [comment]
@tony thanks for your proposal. together with angelo we decided to go with #50

**Pull request closed without merging**
