### PR TITLE
Add Django 3.0 / Python 3.8 support

### LINKED ISSUE #48: Django 3 issues - six is no longer availiable in django.utils
Hello!
"SIX" is not available in django.utils in Django 3, since all python 2 support is dropped.
So importing "SIX" in core.py throws exception.

### PR DESCRIPTION
**Pull request by yakky**
Merge existing partial PR into one to support django 3.0 / Python 3.8

Fix #46 
Fix #47 
Fix #49 
Fix #48
Fix #51

### CODE REVIEW

**Comment by tony** [comment]
@yakky : Is this ready to go in? (Other than it pending a review?)

This is a package downstream in https://github.com/hellysmile/django-activeurl

**Comment by tony** [comment]
@yakky On the other hand, six isn't really being used a lot: https://github.com/divio/django-classy-tags/search?q=six&unscoped_q=six

It may be enough to just do a compat module.

**Comment by tony** [comment]
e.g. *_compat.py*:
```python
import sys
PY2 = sys.version_info[0] == 2

if PY2:
    string_types = (basestring,)
else:
    string_types = (str,)
```

As for the `six.next()`, python 2.6 and above is okay with `next()` since it's a builtin ([link](https://six.readthedocs.io/#six.next))

**Comment by tony** [comment]
@yakky I added an example of compat module based on your branch in #51

**Comment by yakky** [comment]
as agreed with @FinalAngel I am going to merge this solution for Django 3.0 support

**Comment by mbi** [comment]
Thank you @yakky and @FinalAngel! Do you think we can expect a 1.0.0 release on pypi anytime soon?

**Pull request merged**
