### PR TITLE
drop testing for Django < 1.11, add testing for Django 1.11, 2.0, and 2.1

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Hello @ojii @czpython @FinalAngel.
Could you please merge this pull request and update version at PyPi to 0.9? 
This PR is ready to be merged.
If you need help or some changes in this PR, ping me and I will do it.

Also, thanks @timgraham for your contribution to other packages with upgrading code to django>=1.11

**Comment by FinalAngel** [comment]
@DmytroLitvinov I'll have a look as soon as I can :)

**Comment by DmytroLitvinov** [comment]
Great!👍

**Comment by FinalAngel** [comment]
Trying to get release rights to get it on PyPi :)

**Comment by DmytroLitvinov** [comment]
Thank you, Angelo, for report! 👍

**Pull request merged**
